import pytest
from pyspark.sql import SparkSession
import shutil
import os

@pytest.fixture(scope="session")
def spark() -> SparkSession:
    """
    Fixture for creating a local SparkSession with Delta Lake support.
    Will be shared across all unit tests and cleaned up after execution.
    """
    # Force spark to run locally with 2 cores and delta configuration
    spark_session = (
        SparkSession.builder
        .master("local[2]")
        .appName("ETL-Pipeline-Unit-Tests")
        .config("spark.jars.packages", "io.delta:delta-spark_2.12:3.1.0")
        .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
        .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
        .config("spark.sql.shuffle.partitions", "1")  # Single partition for fast testing
        .config("spark.sql.adaptive.enabled", "false") # Disable adaptive queries during test mocks
        .getOrCreate()
    )
    
    yield spark_session
    
    # Tear down session
    spark_session.stop()
    
    # Cleanup any local metastore_db or derby.log generated by Spark
    for path in ["metastore_db", "derby.log", "spark-warehouse"]:
        if os.path.exists(path):
            if os.path.isdir(path):
                shutil.rmtree(path)
            else:
                os.remove(path)
